/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace NotebookProof {
      
    export type ProofDataStruct = {notebookHash: BytesLike, owner: AddressLike, notebookTitle: string, timestamp: BigNumberish, transactionHash: string, exists: boolean}

    export type ProofDataStructOutput = [notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string, exists: boolean] & {notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string, exists: boolean }
  
    }

  export interface NotebookProofInterface extends Interface {
    getFunction(nameOrSignature: "getOwnerNotebooks" | "getProofCount" | "getPublishedBlock" | "ownerNotebooks" | "proofExists" | "proofs" | "publishProof" | "publishedAtBlock" | "verifyProof"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "NotebookProofPublished" | "NotebookProofUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'getOwnerNotebooks', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getProofCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPublishedBlock', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'ownerNotebooks', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'proofExists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'proofs', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'publishProof', values: [BytesLike, string, string]): string;
encodeFunctionData(functionFragment: 'publishedAtBlock', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyProof', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getOwnerNotebooks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProofCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPublishedBlock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerNotebooks', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishedAtBlock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyProof', data: BytesLike): Result;
  }

  
    export namespace NotebookProofPublishedEvent {
      export type InputTuple = [notebookHash: BytesLike, owner: AddressLike, notebookTitle: string, timestamp: BigNumberish, transactionHash: string];
      export type OutputTuple = [notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string];
      export interface OutputObject {notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace NotebookProofUpdatedEvent {
      export type InputTuple = [notebookHash: BytesLike, owner: AddressLike, notebookTitle: string, timestamp: BigNumberish, transactionHash: string];
      export type OutputTuple = [notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string];
      export interface OutputObject {notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NotebookProof extends BaseContract {
    
    connect(runner?: ContractRunner | null): NotebookProof;
    waitForDeployment(): Promise<this>;

    interface: NotebookProofInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getOwnerNotebooks: TypedContractMethod<
      [owner: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getProofCount: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getPublishedBlock: TypedContractMethod<
      [notebookHash: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    ownerNotebooks: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    proofExists: TypedContractMethod<
      [notebookHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    proofs: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, bigint, string, boolean] & {notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string, exists: boolean }],
      'view'
    >
    

    
    publishProof: TypedContractMethod<
      [notebookHash: BytesLike, notebookTitle: string, transactionHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    publishedAtBlock: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    verifyProof: TypedContractMethod<
      [notebookHash: BytesLike, ],
      [[boolean, NotebookProof.ProofDataStructOutput] & {exists: boolean, proof: NotebookProof.ProofDataStructOutput }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getOwnerNotebooks'): TypedContractMethod<
      [owner: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getProofCount'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPublishedBlock'): TypedContractMethod<
      [notebookHash: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ownerNotebooks'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proofExists'): TypedContractMethod<
      [notebookHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'proofs'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, string, bigint, string, boolean] & {notebookHash: string, owner: string, notebookTitle: string, timestamp: bigint, transactionHash: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'publishProof'): TypedContractMethod<
      [notebookHash: BytesLike, notebookTitle: string, transactionHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'publishedAtBlock'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifyProof'): TypedContractMethod<
      [notebookHash: BytesLike, ],
      [[boolean, NotebookProof.ProofDataStructOutput] & {exists: boolean, proof: NotebookProof.ProofDataStructOutput }],
      'view'
    >;

    getEvent(key: 'NotebookProofPublished'): TypedContractEvent<NotebookProofPublishedEvent.InputTuple, NotebookProofPublishedEvent.OutputTuple, NotebookProofPublishedEvent.OutputObject>;
getEvent(key: 'NotebookProofUpdated'): TypedContractEvent<NotebookProofUpdatedEvent.InputTuple, NotebookProofUpdatedEvent.OutputTuple, NotebookProofUpdatedEvent.OutputObject>;

    filters: {
      
      'NotebookProofPublished(bytes32,address,string,uint256,string)': TypedContractEvent<NotebookProofPublishedEvent.InputTuple, NotebookProofPublishedEvent.OutputTuple, NotebookProofPublishedEvent.OutputObject>;
      NotebookProofPublished: TypedContractEvent<NotebookProofPublishedEvent.InputTuple, NotebookProofPublishedEvent.OutputTuple, NotebookProofPublishedEvent.OutputObject>;
    

      'NotebookProofUpdated(bytes32,address,string,uint256,string)': TypedContractEvent<NotebookProofUpdatedEvent.InputTuple, NotebookProofUpdatedEvent.OutputTuple, NotebookProofUpdatedEvent.OutputObject>;
      NotebookProofUpdated: TypedContractEvent<NotebookProofUpdatedEvent.InputTuple, NotebookProofUpdatedEvent.OutputTuple, NotebookProofUpdatedEvent.OutputObject>;
    
    };
  }