'use client'

import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import { PixelPdfIcon, PixelDocIcon } from '@/components/pixel-icons'
import { Eye, FileText, Image as ImageIcon, CheckCircle, AlertTriangle } from 'lucide-react'

interface VisualSnippet {
  id: string
  storageKey: string
  publicUrl: string
  signedUrl: string
  localPath: string
  width: number
  height: number
  mimeType: string
  subType?: string
  source?: string
}

export default function AssetInspectorPage() {
  const [notes, setNotes] = useState<any[]>([])
  const [selectedNote, setSelectedNote] = useState<any | null>(null)
  const [snippets, setSnippets] = useState<VisualSnippet[]>([])
  const [loading, setLoading] = useState(true)
  const [imageStates, setImageStates] = useState<Record<string, 'loading' | 'loaded' | 'failed'>>({})

  const supabase = createClient()

  useEffect(() => {
    async function loadNotes() {
      try {
        const { data, error } = await supabase
          .from('master_notes')
          .select('*, note_sections(*)')
          .eq('generated', true)
        
        if (!error && data) {
          setNotes(data)
          if (data.length > 0) {
            handleSelectNote(data[0])
          }
        }
      } catch (err) {
        console.error('Failed to load notes for inspector:', err)
      } finally {
        setLoading(false)
      }
    }
    loadNotes()
  }, [supabase])

  const handleSelectNote = (note: any) => {
    setSelectedNote(note)
    const list: VisualSnippet[] = []
    
    // Parse visual snippets from ocr_source of sections
    if (note.note_sections) {
      for (const section of note.note_sections) {
        try {
          if (section.ocr_source) {
            const parsed = JSON.parse(section.ocr_source)
            if (parsed.visualAssets && Array.isArray(parsed.visualAssets)) {
              for (const va of parsed.visualAssets) {
                list.push({
                  ...va,
                  source: va.source || `${note.title} (Section: ${section.heading})`
                })
              }
            }
          }
        } catch (e) {
          console.error('Error parsing section ocr_source:', e)
        }
      }
    }
    setSnippets(list)
    
    // Reset image load statuses
    const initialStates: Record<string, 'loading' | 'loaded' | 'failed'> = {}
    list.forEach(s => {
      initialStates[s.id] = 'loading'
    })
    setImageStates(initialStates)
  }

  const checkImageLoad = (id: string, status: 'loaded' | 'failed') => {
    setImageStates(prev => ({
      ...prev,
      [id]: status
    }))
  }

  return (
    <div className="page-shell max-w-6xl mx-auto py-8 px-4">
      <header className="page-header mb-8 flex flex-col gap-2">
        <div className="flex items-center gap-2.5">
          <ImageIcon className="size-6 text-accent" />
          <h1 className="text-2xl font-bold tracking-tight text-foreground font-brand">Asset Inspector</h1>
        </div>
        <p className="text-sm text-muted-foreground">
          Trace, debug, and preview every visual snippet crop generated by the compiler.
        </p>
      </header>

      {loading ? (
        <div className="flex items-center justify-center min-h-[200px] text-muted-foreground text-sm">
          <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-accent" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          Loading assets...
        </div>
      ) : notes.length === 0 ? (
        <div className="border border-dashed border-border p-8 rounded-lg text-center text-muted-foreground">
          No compiled master notes found. Please compile a notebook first to inspect its assets.
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          {/* Note selector side-panel */}
          <div className="md:col-span-1 border border-border/80 bg-card/20 rounded-lg p-4 flex flex-col gap-3">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-1">
              Select Notebook
            </h2>
            <div className="flex flex-col gap-1.5">
              {notes.map(n => (
                <button
                  key={n.id}
                  onClick={() => handleSelectNote(n)}
                  className={`text-left text-xs p-2.5 rounded transition-all duration-200 flex items-center gap-2 border ${
                    selectedNote?.id === n.id
                      ? 'bg-accent/10 border-accent/30 text-accent font-medium'
                      : 'border-transparent hover:bg-muted text-muted-foreground hover:text-foreground'
                  }`}
                >
                  <FileText className="size-3.5 shrink-0" />
                  <span className="truncate">{n.title}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Asset detail dashboard */}
          <div className="md:col-span-3 flex flex-col gap-6">
            <div className="border border-border/80 bg-card/25 rounded-lg p-5">
              <h2 className="text-sm font-bold text-foreground mb-4">
                Visual Snippets for &ldquo;{selectedNote?.title}&rdquo; · {snippets.length}
              </h2>

              {snippets.length === 0 ? (
                <p className="text-xs text-muted-foreground py-4">
                  No visual assets found in this compiled note.
                </p>
              ) : (
                <div className="flex flex-col gap-6">
                  {snippets.map((sn, idx) => {
                    const status = imageStates[sn.id] || 'loading'
                    return (
                      <div key={sn.id} className="border border-border/60 rounded-lg bg-card/10 overflow-hidden">
                        <div className="bg-card/40 px-4 py-2 border-b border-border/60 flex items-center justify-between text-xs font-mono text-muted-foreground">
                          <span>Snippet #{idx + 1} ({sn.subType || 'Visual crop'})</span>
                          <span className="flex items-center gap-1.5">
                            {status === 'loading' && (
                              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] bg-blue-50 text-blue-700 animate-pulse">
                                ⟳ Loading...
                              </span>
                            )}
                            {status === 'loaded' && (
                              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] bg-green-50 text-green-700">
                                <CheckCircle className="size-2.5" />
                                Valid Load
                              </span>
                            )}
                            {status === 'failed' && (
                              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] bg-red-50 text-red-700">
                                <AlertTriangle className="size-2.5" />
                                Load Failed
                              </span>
                            )}
                          </span>
                        </div>

                        <div className="p-4 grid grid-cols-1 lg:grid-cols-2 gap-4">
                          {/* Left Column: Preview */}
                          <div className="flex flex-col items-center justify-center bg-zinc-950/20 dark:bg-black/45 p-4 rounded border border-border/40 min-h-[180px]">
                            {/* preview image */}
                            <img
                              src={sn.localPath}
                              alt={sn.subType || 'Crop Preview'}
                              className="max-h-[160px] object-contain rounded shadow-sm border border-border bg-card"
                              onLoad={() => checkImageLoad(sn.id, 'loaded')}
                              onError={() => checkImageLoad(sn.id, 'failed')}
                            />
                          </div>

                          {/* Right Column: Metadata logs */}
                          <div className="flex flex-col gap-2 text-xs font-mono">
                            <div className="flex justify-between border-b border-border/30 pb-1">
                              <span className="text-muted-foreground font-sans">Storage Key:</span>
                              <span className="text-foreground text-right max-w-[200px] truncate" title={sn.storageKey}>
                                {sn.storageKey.split('/').pop()}
                              </span>
                            </div>
                            <div className="flex justify-between border-b border-border/30 pb-1">
                              <span className="text-muted-foreground font-sans">Local Cached Path:</span>
                              <span className="text-foreground text-right max-w-[200px] truncate" title={sn.localPath}>
                                {sn.localPath}
                              </span>
                            </div>
                            <div className="flex justify-between border-b border-border/30 pb-1 border-dashed">
                              <span className="text-muted-foreground font-sans">Dimensions:</span>
                              <span className="text-foreground">
                                {sn.width} × {sn.height} px
                              </span>
                            </div>
                            <div className="flex justify-between border-b border-border/30 pb-1 border-dashed">
                              <span className="text-muted-foreground font-sans">Mime Type:</span>
                              <span className="text-foreground">{sn.mimeType}</span>
                            </div>
                            <div className="flex flex-col gap-1 mt-2">
                              <span className="text-muted-foreground font-sans">Resolved public URL:</span>
                              <a
                                href={sn.publicUrl}
                                target="_blank"
                                rel="noreferrer"
                                className="text-[10px] text-accent hover:underline truncate"
                              >
                                {sn.publicUrl}
                              </a>
                            </div>
                            <div className="flex flex-col gap-1 mt-1">
                              <span className="text-muted-foreground font-sans">Signed URL (1 Year):</span>
                              <a
                                href={sn.signedUrl}
                                target="_blank"
                                rel="noreferrer"
                                className="text-[10px] text-accent hover:underline truncate"
                              >
                                {sn.signedUrl}
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
